version: '2'

services:
  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRESQL_DB: postgres
      POSTGRESQL_USER: postgres

  web:
    restart: always
    # Docker hack to wait until Postgres is up, then run stuff.
    command: bash -c "while ! nc -w 1 -z db 5432; do sleep 0.1; done; python manage.py migrate; while :; do python manage.py runserver 0.0.0.0:8000; sleep 1; done"
    image: bl4ckpr15m
    volumes:
      - .:/code
    build: .
    depends_on:
      - db
    environment:
      IN_DOCKER: 1
    ports:
      - "8000:8000"

  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "80:8000"
    command: -port 8000 -host 0.0.0.0 "proxy / web:8000 { }"
